import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'
import Button from "../components/button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1 className={styles.title}>
              LFD Reader Demo
          </h1>

          <Link href="reader">
              <img src="http://placekitten.com/300" style={{marginTop: "1rem", marginBottom: "1rem"}}/>
          </Link>

          <Link href="test" >
              <Button>Debug here</Button>
          </Link>
      </main>

      <footer className={styles.footer}>
          <span className={styles.logo}>
            <Image src="/AIT_logo-1.webp" width={144} height={32}/>
          </span>
      </footer>
    </div>
  )
}
